services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    BinSoul\Symfony\Bundle\Content\Repository\:
        resource: '../../Repository/*'
        public: true

    BinSoul\Symfony\Bundle\Content\EventListener\:
        resource: '../../EventListener/*'
        tags: ['kernel.event_subscriber']

    BinSoul\Symfony\Bundle\Content\EventListener\TablePrefixListener:
        tags: ['doctrine.event_subscriber']

    BinSoul\Symfony\Bundle\Content\EventListener\SynchronizePageTranslationListener:
        tags: ['doctrine.event_subscriber']
