services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    BinSoul\Symfony\Bundle\Content\Repository\:
        resource: '../../Repository/*'
        public: true

    BinSoul\Symfony\Bundle\Content\EventListener\PageListener:
        tags: ['kernel.event_subscriber']

    BinSoul\Symfony\Bundle\Content\EventListener\TwigGlobalsListener:
        tags: ['kernel.event_subscriber']

    BinSoul\Symfony\Bundle\Content\EventListener\TablePrefixListener:
        public: true

    BinSoul\Symfony\Bundle\Content\EventListener\SynchronizeElementRelationListener:
        public: true

    BinSoul\Symfony\Bundle\Content\EventListener\SynchronizeElementTranslationListener:
        public: true

    BinSoul\Symfony\Bundle\Content\EventListener\SynchronizePageTranslationListener:
        public: true

    BinSoul\Symfony\Bundle\Content\Element\Type\:
        resource: '../../Element/Type'
        tags: ['content_element_type']

    BinSoul\Symfony\Bundle\Content\Element\DefaultTypeFactory:
        public: true
        arguments: [!tagged 'content_element_type']

    BinSoul\Symfony\Bundle\Content\Element\TypeFactory: '@BinSoul\Symfony\Bundle\Content\Element\DefaultTypeFactory'

    BinSoul\Symfony\Bundle\Content\Page\DefaultRenderer:
        public: true

    BinSoul\Symfony\Bundle\Content\Page\Renderer: '@BinSoul\Symfony\Bundle\Content\Page\DefaultRenderer'
